// cases.js
// showCases implementation (cases flow with steps)

function showCases(topic, body, footer, metrics) {
  return new Promise((resolve) => {
    body.innerHTML = "";
    footer.innerHTML = `<div>Prípady</div>`;
    const cases = Array.isArray(topic.cases) ? topic.cases : [];
    if (cases.length === 0) {
      footer.innerHTML = `<button class="primary-btn btn-continue click-anim">Preskočiť prípady</button>`;
      footer.querySelector(".btn-continue").addEventListener("click", () => resolve());
      return;
    }

    let totalCorrect = 0;
    let caseIndex = 0;
    metrics.cases.totalSteps = 0;
    metrics.cases.correctSteps = 0;

    function renderCase() {
      const c = cases[caseIndex];
      body.innerHTML = `<div class="case-block"><h3>${escapeHtml(c.title || "")}</h3></div>`;
      const cb = body.querySelector(".case-block");
      let stepIndex = 0;

      function renderStep() {
        const s = c.steps[stepIndex];
        const stepEl = document.createElement("div");
        stepEl.className = "case-step";

        if (!s.options || s.options.length === 0) {
          stepEl.innerHTML = `<p><strong>${escapeHtml(s.question || "")}</strong></p>
            <div style="margin-top:12px"><button class="primary-btn btn-next click-anim">Pokračovať na Krok 1</button></div>`;
          cb.appendChild(stepEl);
          stepEl.querySelector(".btn-next").addEventListener("click", () => {
            stepIndex++;
            renderNextOrFinish();
          });
          return;
        }

        stepEl.innerHTML = `<p><strong>${escapeHtml(s.question || "")}</strong></p>
          <div class="case-options" style="margin-top:8px"></div>
          <div class="case-expl" aria-live="polite" style="margin-top:8px"></div>
          <div class="case-controls" style="margin-top:12px"></div>
        `;
        const opts = stepEl.querySelector(".case-options");
        const expl = stepEl.querySelector(".case-expl");
        const controls = stepEl.querySelector(".case-controls");

        if (s.autoGenerated) {
          const badge = document.createElement("span");
          badge.textContent = "auto";
          badge.style.marginLeft = "10px";
          badge.style.padding = "4px 8px";
          badge.style.fontSize = "12px";
          badge.style.borderRadius = "999px";
          badge.style.background = "rgba(217,165,179,0.12)";
          badge.style.color = "var(--accent)";
          badge.style.fontWeight = "700";
          const titleEl = stepEl.querySelector("p strong");
          if (titleEl) titleEl.insertAdjacentElement("afterend", badge);
        }

        (s.options || []).forEach((opt, i) => {
          const b = document.createElement("button");
          b.className = "primary-btn click-anim";
          b.style.marginRight = "8px";
          b.textContent = `${String.fromCharCode(65 + i)}. ${opt}`;
          b.addEventListener("click", () => {
            opts.querySelectorAll("button").forEach(x => x.disabled = true);
            const correct = Number.isFinite(s.correct) ? s.correct : 0;
            metrics.cases.totalSteps++;
            if (i === correct) {
              expl.textContent = s.explanation_correct || "Správne.";
              expl.style.color = "inherit";
              metrics.cases.correctSteps++;
            } else {
              expl.textContent = s.explanation_incorrect || `Nesprávne. Správna odpoveď: ${s.options[correct] || "—"}`;
              expl.style.color = "inherit";
              const correctBtn = opts.querySelectorAll("button")[correct];
              if (correctBtn) correctBtn.style.outline = "3px solid rgba(34,139,34,0.18)";
            }
            controls.innerHTML = `<button class="primary-btn btn-next click-anim">Ďalšia</button>`;
            controls.querySelector(".btn-next").addEventListener("click", () => {
              stepIndex++;
              renderNextOrFinish();
            });
          });
          opts.appendChild(b);
        });

        cb.appendChild(stepEl);
      }

      function renderNextOrFinish() {
        cb.innerHTML = `<h3>${escapeHtml(c.title || "")}</h3>`;
        if (stepIndex < (c.steps || []).length) {
          renderStep();
        } else {
          const summary = document.createElement("div");
          summary.style.marginTop = "12px";
          summary.innerHTML = `<div>Prípad dokončený.</div>
            <div style="margin-top:10px"><button class="primary-btn btn-next-case click-anim">Ďalší prípad</button></div>`;
          cb.appendChild(summary);
          summary.querySelector(".btn-next-case").addEventListener("click", () => {
            caseIndex++;
            if (caseIndex < cases.length) renderCase();
            else resolve();
          });
        }
      }

      renderStep();
    }

    renderCase();
  });
}
